query GetOrders(
  $statuses: [OrderStatusEnum!]
  $table_id: ID
  $first: Int = 50
  $page: Int = 1
) {
  orders(statuses: $statuses, table_id: $table_id, first: $first, page: $page) {
    paginatorInfo {
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
    data {
      id
      price
      status
      table {
        id
        label
        room {
          id
          name
        }
      }
      steps {
        stepMenus {
          menu {
            name
          }
        }
      }
    }
  }
}
