query GetLocations($first: Int, $page: Int, $orderBy: [OrderByClause!]) {
  locations(first: $first, page: $page, orderBy: $orderBy) {
    data {
      id
      name
      created_at
      updated_at
      locationType {
        id
        name
        is_default
      }
    }
    paginatorInfo {
      count
      currentPage
      hasMorePages
      lastPage
      perPage
      total
      firstItem
      lastItem
    }
  }
}
