query GetMenuById($id: ID!) {
  menu(id: $id) {
    id
    name
    image_url
    price
    description
    type
    allergens
    categories {
      ...MenuCategoryBasic
    }
    available
    is_a_la_carte
    items {
      ...MenuItemBasic
      entity {
        ... on Preparation {
          ...PreparationBase
          ...PreparationQuantitiesBasic
        }
        ... on Ingredient {
          ...IngredientBase
          ...IngredientQuantitiesBasic
        }
      }
    }
  }
}
