query getMenus($page: Int!, $first: Int! = 10, $available: Boolean) {
  menus(page: $page, first: $first, available: $available) {
    data {
      id
      name
      image_url
      description
      public_priority
      menu_type_id
      service_type
      is_returnable
      price
      is_a_la_carte
      available
      created_at
      updated_at
      items {
        id
        quantity
        unit
        location {
          id
          name
        }
      }
    }
    paginatorInfo {
      count
      currentPage
      hasMorePages
      lastPage
      perPage
      total
      firstItem
      lastItem
    }
  }
}
