query GetPreparations($page: Int!, $search: String) {
  preparations(page: $page, search: $search) {
    data {
      id
      name
      image_url
      allergens
      unit
      quantities {
        quantity
        location {
          id
          name
        }
      }
      categories {
        id
        name
      }
    }
    paginatorInfo {
      hasMorePages
      currentPage
    }
  }
}
