query GetRooms($first: Int! = 10, $page: Int = 1, $search: String) {
  rooms(first: $first, page: $page, search: $search) {
    data {
      id
      code
      name
      tables {
        id
        label
        seats
        orders {
          id
          price
          status
          created_at
          pending_at
        }
      }
    }
    paginatorInfo {
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
  }
}
