query GetMenuCategories($first: Int, $page: Int) {
  menuCategories(first: $first, page: $page) {
    data {
      name
      id
      created_at
      updated_at
    }
    paginatorInfo {
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
  }
}
