query GetIngredient($id: ID!) {
  ingredient(id: $id) {
    ...IngredientFull
    stockMovements {
      quantity_before
      quantity_after
      type
      created_at
      location {
        id
      }
    }
  }
}
