query GetOrders(
  $statuses: [OrderStatusEnum!]
  $table_id: ID
  $first: Int = 50
  $page: Int = 1
  $start_date: DateTime
  $end_date: DateTime
) {
  orders(
    statuses: $statuses
    table_id: $table_id
    first: $first
    page: $page
    start_date: $start_date
    end_date: $end_date
  ) {
    paginatorInfo {
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
    data {
      id
      price
      status
      created_at
      pending_at
      served_at
      payed_at
      table {
        id
        label
        room {
          id
          name
        }
      }
      steps {
        stepMenus {
          menu {
            name
          }
        }
      }
    }
  }
}
