query searchIngredients($searchTerm: String!) {
  searchInStock(keyword: $searchTerm) {
    ... on Ingredient {
      ...IngredientBase
      allergens
      ...IngredientQuantitiesBasic
    }
    ... on Preparation {
      ...PreparationBase
      allergens
      ...PreparationQuantitiesBasic
    }
  }
}
