query getCompanyProducts($name: String, $page: Int!) {
  ingredients(name: $name, page: $page) {
    data {
      id
      name
      image_url
      unit
      quantities {
        quantity
        location {
          id
          name
        }
      }
    }
  }
}
