query getCompanyProducts($searchQuery: String, $page: Int!) {
  ingredients(search: $searchQuery, page: $page) {
    data {
      id
      name
      image_url
      unit
      quantities {
        quantity
        location {
          id
          name
        }
      }
    }
    paginatorInfo {
      hasMorePages
    }
  }
}
