query getIngredient($id: ID, $barcode: String) {
  ingredient(id: $id, barcode: $barcode) {
    id
    image_url
    name
    category {
      name
      id
    }
    unit
    base_quantity
    base_unit
    quantities {
      location {
        id
        name
        locationType {
          name
        }
      }
      quantity
    }
  }
}
