query getItemByInternalId($id: ID) {
  ingredient(id: $id) {
    id
    image_url
    name
    categories {
      name
      id
    }
    unit
    base_quantity
    quantities {
      location {
        id
        name
      }
      quantity
    }
  }
}
